
name: 'dbt_tripadvisor'
version: '1.0.0'

profile: 'dbt_tripadvisor'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  +schema: models

models:
  dbt_tripadvisor:
    staging:
      +materialized: table
      +schema: models
    intermediate:
      +materialized: view
      +schema: models
    marts:
      +materialized: table

vars:
  min_date: null
  max_date: null